version: '3.4'

services:
  ratechecker:
    image: ${DOCKER_REGISTRY-}ratechecker
    build:
      context: .
      dockerfile: RateChecker/Dockerfile
    depends_on:
        - selenoid
    ports:
        - 7035:7035
    networks:
      - selenoid

  selenoid:
    image: aerokube/selenoid:1.11.0
    environment:
      - DOCKER_API_VERSION=1.41
    volumes:
      - "./selenoid_config:/etc/selenoid"
      - "./selenoid_config/video:/opt/selenoid/video"
      - "./selenoid_config/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      selenoid: null
    ports:
      - 4444:4444
    restart: always
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    environment:
      - DOCKER_API_VERSION=1.41
    networks:
      - selenoid
    links:
      - selenoid
    ports:
      - 8080:8080
    restart: always
    command: ["--selenoid-uri", "http://selenoid:4444"]

  proxy:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on: 
      - ratechecker
    ports:
      - 80:80
      - 443:443
    tty: true
    environment:
      - SERVER_NAME=${SERVER_NAME}  

volumes:
  dbdata:

networks:
  selenoid:
    external:
      name: selenoid  

